[env:esp32-s3-jc3248w535]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32.git ; v3.3.9 em 22/07/2026
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_filters = esp32_exception_decoder
build_type = debug
board_build.filesystem = littlefs
; boards_dir = boards
; data_dir = littlefs
; lib_dir = libraries
; src_dir = src

; --- Configurações de Flash ---
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L

; --- Configurações de PSRAM (OPI) ---
; Essencial para módulos com 16MB Flash / 8MB PSRAM
board_build.arduino.memory_type = qio_opi 

; --- Flags de Compilação (Build Flags) ---
build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    ; Diz ao compilador para procurar arquivos .h na pasta include
    -I include 
    -D CORE_DEBUG_LEVEL=3   ; Ativa logs do sistema
    
; --- Dependências ---
lib_deps =
    lvgl/lvgl @ 8.4.0
    bblanchon/ArduinoJson @ ^7.4.3
    ; Adicione aqui outras bibliotecas que seu projeto utiliza (TFT_eSPI, LovyanGFX, etc.)
